# Generated by Django 5.0 on 2025-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('server_ip', models.CharField(max_length=100)),
                ('server_port', models.IntegerField()),
                ('server_status', models.CharField(choices=[('0', '空闲'), ('1', '繁忙'), ('2', '离线')], max_length=100)),
                ('server_create_time', models.DateTimeField(auto_now_add=True)),
                ('server_token', models.CharField(max_length=100)),
                ('server_HeartTime', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False, help_text='是否禁用')),
            ],
            options={
                'db_table': 'judge_server',
            },
        ),
    ]
