# Generated by Django 5.0 on 2025-05-22 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(default='新对话', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AI.knowledgebase')),
            ],
            options={
                'db_table': 'ai_chat_session',
                'indexes': [models.Index(fields=['user', 'last_active'], name='ai_chat_ses_user_id_baecc1_idx')],
            },
        ),
    ]
