# Generated by Django 5.0 on 2025-05-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
