# Generated by Django 5.0 on 2025-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='announcements',
            field=models.ManyToManyField(to='home.announcement'),
        ),
    ]
