# Generated by Django 5.0 on 2025-05-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionproblem',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
