# Generated by Django 5.0 on 2025-05-12 13:11

import django.db.models.deletion
import django_ckeditor_5.fields
import problem.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'problem_tag',
            },
        ),
        migrations.CreateModel(
            name='ProblemTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(blank=True, default='default_problem', max_length=255, null=True)),
                ('test', models.JSONField()),
            ],
            options={
                'db_table': 'problem_test',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.TextField()),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('samples', problem.models.RichTextJSONField(encoder=problem.models.RichTextJSONEncoder, help_text="示例输入输出，支持富文本格式。格式为: [{'input': '<p>输入内容</p>', 'output': '<p>输出内容</p>'}, ...]")),
                ('run_test', problem.models.RichTextJSONField(blank=True, encoder=problem.models.RichTextJSONEncoder, help_text='和samples一样', null=True)),
                ('hint', django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ('languages', models.JSONField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.JSONField()),
                ('memory_limit', models.JSONField()),
                ('Stack_memory_limit', models.IntegerField(blank=True, null=True)),
                ('template', problem.models.RichTextJSONField(blank=True, encoder=problem.models.RichTextJSONEncoder, null=True)),
                ('mode', models.TextField(default='OI')),
                ('visible', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('1', 'Low'), ('2', 'Mid'), ('3', 'High')], default='1', max_length=20)),
                ('source', models.TextField(blank=True, null=True)),
                ('submission_number', models.BigIntegerField(default=0)),
                ('accepted_number', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='problem.problemtag')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_problems', to='problem.problemtest')),
            ],
            options={
                'db_table': 'problem',
                'ordering': ('create_time',),
                'unique_together': {('_id',)},
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('result', models.JSONField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Run',
                'ordering': ('submit_time',),
            },
        ),
    ]
